remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Andrii Novikov
description: |
  <h3>Lead Software Engineer</h3>

  <ul style="list-style-type: none; padding: 0;">
    <li>âœ‰ï¸ <a target="_blank" href="mailto:andrii.novikov@gmail.com">andrii.novikov@gmail.com</a></li>
    <li >ğŸ”— <a target="_blank" href="https://www.linkedin.com/in/andrii-novikov-652197156/">LinkedIn</a> </li>
    <li>ğŸ”— <a target="_blank" href="https://github.com/andrii-novikov">GitHub</a></li>
  </ul>

logo: /assets/an.jpeg
show_downloads: false
# google_analytics:
# theme: jekyll-theme-minimal
